routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
	/* When it goes live */
    return view('welcome');
    // return view('welcome2');

});

// Route::get('/welcomedemo', function () {
	// /* When it goes live */
    // return view('welcome');
    // return view('welcome2');

// });


Route::get('/agency', function () {
    return view('agencylanding');
});

Route::get('/signup',function(){
	return view('modelling.signupmodel');
});



//Only agency
Route::group(['prefix' => 'agency'], function () {
  Route::get('/login', 'AgencyAuth\LoginController@showLoginForm');
  Route::post('/login', 'AgencyAuth\LoginController@login');
  Route::post('/logout', 'AgencyAuth\LoginController@logout');

  Route::get('/register', 'AgencyAuth\RegisterController@showRegistrationForm');
  Route::get('/register2', 'AgencyAuth\RegisterController@showRegistrationForm2');
  Route::post('/register', 'AgencyAuth\RegisterController@register');

  //Yourname checker
  Route::post('/yourname', 'AgencyAuth\RegisterController@yourname');

  Route::post('/password/email', 'AgencyAuth\ForgotPasswordController@sendResetLinkEmail');
  Route::post('/password/reset', 'AgencyAuth\ResetPasswordController@reset');
  Route::get('/password/reset', 'AgencyAuth\ForgotPasswordController@showLinkRequestForm');
  Route::get('/password/reset/{token}', 'AgencyAuth\ResetPasswordController@showResetForm');


  Route::model('jobs', 'Job');
  Route::resource('jobs', JobsController::class); // Finds the corresponding routes. Use this to make the system faster


  // Any new routes... please go to agency.php. Else... no authenticated user
});

//Only for the modelsearch. The human models
Route::group(['prefix' => 'modelsearch'], function () {
	Route::get('', 'VotingAuth\LoginController@showLoginForm');
	Route::post('', 'VotingAuth\LoginController@login');
	Route::post('/logout', 'VotingAuth\LoginController@logout');
	Route::get('/redirectv', 'SocialAuthController@redirectV');
	Route::get('/callback', 'SocialAuthController@callbackV');
});

//Models search
Route::group(['prefix'=>'models'],function(){

  // Modelling setting
  Route::get('/home', 'Modelling@index');
  Route::get('/registration', 'Modelling@registration');
	Route::post('/yourname', 'Modelling@yourname');
  Route::get('/update', 'Modelling@update');
  Route::get('/profile', 'Modelling@profile');
  Route::post('/profile', 'FileUploadController@update_avatar');
  Route::patch('/img_upload', 'FileUploadController@imageUploadPost');

  Route::patch('/img_upload2', 'FileUploadController@imageUploadvar2');
  Route::get('/image_upload', 'FileUploadController@imageUploadPost2');
  Route::get('/job_model', 'Modelling@jobs');
  Route::get('/thankyou', 'Modelling@thankyou');

  // Profile pages
  Route::get('/compcard', 'ProfileController@compgen');
  Route::post('/edit_test','ProfileController@store');
  Route::patch('/update_test','ProfileController@update'); // Remember dimwit... If patch, must meet with patch

  // Jobs
  Route::post('/job_test','JobModelController@model_apply');
  Route::post('/book_cancel','JobModelController@booking_cancel');

  //File upload. In this case images
  Route::get('/image_registration','FileUploadController@imageregistration');
  Route::post('/{id}/photos','FileUploadController@addphotos');
  Route::post('/{id}/massphotos','FileUploadController@addmassphotos');
  Route::get('/myphotos','PhotoGallery@index');
  Route::post('/destroyImage','PhotoGallery@destroy');

  Route::get('/bookings', 'Modelling@history');
	Route::get('/image_upload2', 'FileUploadController@imageUploadPost3');

	Route::get('/ratings', 'ModelRatingController@job_rating');
});


Auth::routes();

// Route::get('/home', 'HomeController@index');

//After this we shall try with the model prefix. Have to make it look good
Route::get('/redirect', 'SocialAuthController@redirect');
Route::get('/callback', 'SocialAuthController@callback');

// All them main pages
Route::get('/about', function () { return view('about'); });
Route::get('/plans', function () { return view('plans'); });
Route::get('/terms', function () { return view('terms'); });
Route::get('/privacy', function () { return view('privacy'); });
Route::get('/help', function () { return view('help'); });
Route::get('/contact', function () { return view('contact'); });

Route::get('/{nickname}', 'Modelling@profile2');
Route::get('/a/{nickname}', 'agencyprofilecontroller@agencypublic');
Route::get('/job/{job_id}', 'agencyprofilecontroller@agencypublic');


//Test activation and admin panel
Route::group(['prefix' => 'admintalent'], function () {
  Route::get('/login', 'AdmintalentAuth\LoginController@showLoginForm');
  Route::post('/login', 'AdmintalentAuth\LoginController@login');
  Route::post('/logout', 'AdmintalentAuth\LoginController@logout');

  Route::get('/register', 'AdmintalentAuth\RegisterController@showRegistrationForm');
  Route::post('/register', 'AdmintalentAuth\RegisterController@register');

  Route::post('/password/email', 'AdmintalentAuth\ForgotPasswordController@sendResetLinkEmail');
  Route::post('/password/reset', 'AdmintalentAuth\ResetPasswordController@reset');
  Route::get('/password/reset', 'AdmintalentAuth\ForgotPasswordController@showLinkRequestForm');
  Route::get('/password/reset/{token}', 'AdmintalentAuth\ResetPasswordController@showResetForm');
  Route::get('/activation/{token}', 'AdmintalentAuth\RegisterController@userActivation');
});

app/Agency.php
<?php

namespace App;

use App\Notifications\AgencyResetPassword;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Agency extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new AgencyResetPassword($token));
    }

    public function photos(){
      return $this->hasOne('App\AgencyGallery');
    }



}

resources/views/agency/jobs_bak/create.blade.php
@extends('agency.layout.auth')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create Job</div>
                    @include('agency.jobs.form')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/agency/jobs_bak/edit.blade.php
@extends('agency.layout.auth')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit Job</div>
                    @include('agency.jobs.form')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/agency/jobs_bak/form.blade.php
<div class="panel-body">
    {{ Form::model($job, ['route' => $route, 'method' => $method]) }}
    <div class="form-group">
        {{ Form::label('title', 'Title') }}
        {{ Form::text('title', old('title'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('start_date', 'Start Date') }}
        {{ Form::date('start_date', old('start_date'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('end_date', 'End Date') }}
        {{ Form::date('end_date', old('end_date'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('start_time', 'Start Time') }}
        {{ Form::text('start_time', old('start_time'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('end_time', 'End Time') }}
        {{ Form::text('end_time', old('end_time'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('venue', 'Venue') }}
        {{ Form::text('venue', old('venue'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('location', 'Location') }}
        {{ Form::text('location', old('location'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('gender', 'Gender') }}
        {{ Form::select('gender', [1 => 'Male', 2 => 'Female', 3 => 'Both'], old('gender'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('payment', 'Payment') }}
        {{ Form::text('payment', old('payment'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('payment_terms', 'Payment Terms') }}
        {{ Form::text('payment_terms', old('payment_terms'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('casting_date', 'Casting Date') }}
        {{ Form::date('casting_date', old('casting_date'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('casting_time', 'Casting Time') }}
        {{ Form::text('casting_time', old('casting_time'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('age_min', 'Min Age') }}
        {{ Form::number('age_min', old('age_min'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('age_max', 'Max Age') }}
        {{ Form::number('age_max', old('age_max'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('height_min', 'Min Height') }}
        {{ Form::number('height_min', old('height_min'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('height_max', 'Max Height') }}
        {{ Form::number('height_max', old('height_max'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('ethnicity', 'Ethnicity') }}
        {{ Form::text('ethnicity', old('ethnicity'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('language', 'Language') }}
        {{ Form::text('language', old('language'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('additional_info', 'Additional Info') }}
        {{ Form::text('additional_info', old('additional_info'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::label('status', 'Status') }}
        {{ Form::select('status', [1 => 'Enabled', 0 => 'Disabled'], old('status'), ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        {{ Form::submit('Save', ['class' => 'btn']) }}
    </div>
    {{ Form::close() }}
</div>

resources/views/agency/jobs_bak/index.blade.php
@extends('agency.layout.auth')

@section('content')
    <div class="container">
        @if (Session::has('message'))
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ Session::get('message') }}asd
            </div>
        @endif
        <div class="row">
            {{ link_to_route('jobs.create', 'Create Job', [], ['class' => 'btn btn-info']) }}
            <table class="table table-responsive table-bordered">
                <tr>
                    <td>Title</td>
                    <td>Date</td>
                    <td>Time</td>
                    <td>Action</td>
                </tr>
                @if ($jobs->count() > 0)
                @foreach ($jobs as $job)
                    <tr>
                        <td>{{ $job->title }}</td>
                        <td>{{ $job->casting_date }}</td>
                        <td>{{ $job->casting_time }}</td>
                        <td>
                            <div class="btn-group">
                                {{ Form::open(['route' => ['jobs.destroy', $job->id], 'method' => 'DELETE']) }}
                                    {{ link_to_route('jobs.edit', 'Edit', $job->id, ['class' => 'btn btn-info']) }}
                                    {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
                                {{ Form::close() }}
                            </div>
                        </td>
                    </tr>
                @endforeach
                @else
                    <tr>
                        <td colspan="4">No jobs</td>
                    </tr>
                @endif
            </table>
        </div>
    </div>
@endsection